sudo: required
language: java
jdk: openjdk9
branches:
  only:
  - master
  - dev
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: M57qUoivyvJve4+OI1Ed5yARHtYmWcviBEMySzxpLcHLIrt0hTKuUiNXtKCKKq63Hkx6fRhT+eRSo81azoYmCvuZaKsVvckf3QaVykT60Nxh1T99LdLqfEKVybNHuNJfKEjTo9114t48szLLnZeHfh+kGFLsZufOVzJQvHdI5kcejXLKODOxjLaJw/Nt2VuVzVTo5Qz6U29mOYrXfY4i7jgM7Qm7uvQk6HFz/JJvloNRJXC6pCVRv4JPTusMaHD3bMKSQGIgD7bYE8Jrf3VR1THPW4Sft+kBKGxwIvzKGC/HByItoyDq5UjMOs+hyIgY6NIUAFL98DYfurvo2EDMmFtjcmKwUr4bPpMxSmu22MalNeIVkVh/toj5T9D/DReK0Y0rhj5ycZJpVtevHHwGGbtaFj70+wFXfnY0cwbHAn13E5tkVICQrtlPBsNjn5TvHEn0fiCRiC68rWCp1ofPsvGCmrlqwl9jA2zJ5/8nOLHWAuCbdb+dYRu56mI3qO81/RoH2cFEseTjCucUJZ3vPOLd7jp47LlJdUJY0TBhQKdAJcWHdGWqs8iqe4wTqPiCkEjkJL+6cogyZuSmkSTVOlm2/8XsDnr7AXAlDaP/o2BD3GBxsv2V9tJXYFNC+ZOkXcUY8DzAYfoCM2/U0DgoMj4lF6zi8aiZOz9jwHw7Df8=
  app:
    master: yugioh-database
    dev: yugioh-database
