sudo: required
language: java
jdk: openjdk9
branches:
  only:
  - master
  - dev
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: gKrVz/RmFb1VLHoJ7DlYV2az4lTZeSCzKtP0XmM4P568P5nc9TsytQ7IT78q9vEuGN5QWi706ex4g+QX5lYrQ4MGG0aVXL2Ou5lVUbJEWh2QsjL910v6AyrssGVyAhckc+jQIHmF6pWA3ex57f0dxM+c8ENtuhh17JSMmci4lNKlTVIDME5A2tDME3xhBeuvqqIR5Oqoag7dDHbtE0ce+LHN36/KQ8kvYOZlNEkWHBgpQA8qu2BUJt4N9TXHw0pYOSWcA7XcT2NytR7P7QPkcRis8+d1E5XmcB/+KeQuTQ8YY+XQR3IhB7lnvQ89IpOJsVEmMlSMlq2UHZ9UkYs3eOeOTFXiSiVhliz8q1JmA4AVoJyQM4qGlybwB5u/rWulLokBzzf9wzJZaWfjaEynGtH8VSs/jzPuE7snaAVpj+/hug81pDuzIgI0sLrZEBWVTrE8+o2So1H/8rAX/Xv9ot6vF72vajeaWvEt48eahA+4ablHZaiA7vWycInBNMqbZLrXGStxqCqH/G9PJlMm4cCHnDSx/frISF6P6gpS/8eeOGizrXuQKds6c/e753X7LUKUPP1j5ty9T8p1AjgVijtpbuqPYlGqSN60o4LPELHOmSabK+bQBcF1uvJ6UmpZH1R9bD8smGofqdXf6Bu2AEAa3QMG0ohHzXiMixH/Sj8=
  app:
    master: yugioh-database
    dev: yugioh-database
