sudo: required
language: java
jdk: openjdk9
branches:
  only:
  - master
  - dev
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: fWPuINNOC7Ym4MbN3fva9MCCiMmEZ1Sh4+pzRFcbuXgHE/lFFXnYNgQ33GZw5eWC+IioNIzzSAe0oMKD3YtdwxwPNVFHpi1MvPGQ39Ao13oaT4OMR7zlezDgFvEWeo84cXehzIsMuD6yASx9go8Ocg3m0TlvTw5gksbS+QbJz93/brXVKD923BBIGKhj1IgR996++g2fnH58JHD8FQ8OmAUPYKYX7QHLemZ0i77Ol1TME6mCpj8akDp/AB2pLSYmyeWl2cmnre6NrfgpVUBoldSZXtWVZqr8IS6Kjc/ZbRdc75WaD/f5tXKnxw6IwwkgQ2tWDBDVt1yEv33B5avYSBQA6fWo+AEphM9mW5jk9MJn2HJG044cbdazoUjEXvyxCCWH2dbchWfF6mq0qWcipBCroMFAdgn2kfGVO/pCOqehd5XEcdX8xxHwanE9OER6SFouyE2LY+RDWh3S9SXlW6uO/RKVtlIqKGnOkwZ2PTcwKNv6GweCEHX9MV4LYvIY87S1rDgFyMv17pp0eQV04Rj5ZtUtADemB4EU5Hhl+EXyvFlxcaueFN1CTwiL73HFnscabwMuAgaLw1+qWl0PxuD+uUXBpPpNH9Ag2tdR/cl+Z7Zkp7+v5BO7eq5XjWDFYRmZ7bHtlgw5c01t1zWHRsWWx+6x8PhvCpOpL69D32Y=
  app:
    master: yugioh-database
    dev: yugioh-database
